
services:
  - type: web
    name: buy-me-a-chai
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
